export const STOCKEVENT_CREATE_REQUEST = 'STOCKEVENT_CREATE_REQUEST';
export const STOCKEVENT_CREATE_SUCCESS = 'STOCKEVENT_CREATE_SUCCESS';
export const STOCKEVENT_CREATE_FAIL = 'STOCKEVENT_CREATE_FAIL';

export const STOCKEVENT_LIST_REQUEST = 'STOCKEVENT_LIST_REQUEST';
export const STOCKEVENT_LIST_SUCCESS = 'STOCKEVENT_LIST_SUCCESS';
export const STOCKEVENT_LIST_FAIL = 'STOCKEVENT_LIST_FAIL';

export const STOCKCOUNT_UPDATE_REQUEST = 'STOCKEVENT_UPDATE_REQUEST';
export const STOCKCOUNT_UPDATE_SUCCESS = 'STOCKEVENT_UPDATE_SUCCESS';
export const STOCKCOUNT_UPDATE_FAIL = 'STOCKEVENT_UPDATE_FAIL';

export const STOCKCOUNT_LIST_REQUEST = 'STOCKCOUNT_LIST_REQUEST';
export const STOCKCOUNT_LIST_SUCCESS = 'STOCKCOUNT_LIST_SUCCESS';
export const STOCKCOUNT_LIST_FAIL = 'STOCKCOUNT_LIST_FAIL';
