export const STOCKEVENT_LIST_REQUEST = 'STOCKEVENT_LIST_REQUEST';
export const STOCKEVENT_LIST_SUCCESS = 'STOCKEVENT_LIST_SUCCESS';
export const STOCKEVENT_LIST_FAIL = 'STOCKEVENT_LIST_FAIL';

export const STOCKCOUNT_LIST_REQUEST = 'STOCKCOUNT_LIST_REQUEST';
export const STOCKCOUNT_LIST_SUCCESS = 'STOCKCOUNT_LIST_SUCCESS';
export const STOCKCOUNT_LIST_FAIL = 'STOCKCOUNT_LIST_FAIL';
